CREATE TABLE [bkp].[SSIS_VTX_tixeventzoneseats]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[tixeventid] [numeric] (10, 0) NULL,
[tixeventzoneid] [smallint] NULL,
[tixseatgroupid] [int] NULL,
[tixseatid] [numeric] (10, 0) NULL,
[tixseatdesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatcurrentstatus] [numeric] (10, 0) NULL,
[tixseatecommercehdrlink] [numeric] (10, 0) NULL,
[tixseatecommercedtllink] [int] NULL,
[tixseatseasonticket] [numeric] (10, 0) NULL,
[tixseatbarcode] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatdefltavailstatus] [numeric] (10, 0) NULL,
[tixseatprintcount] [numeric] (10, 0) NULL,
[tixseatnexthistoryptr] [smallint] NULL,
[tixseatprimaryspeccode] [int] NULL,
[tixseatpricecode] [numeric] (10, 0) NULL,
[tixseatvaluebeforediscounts] [numeric] (19, 4) NULL,
[tixseatpriceafterdiscounts] [numeric] (19, 4) NULL,
[tixseatpaidtodate] [numeric] (19, 4) NULL,
[tixseatpricetoprintonticket] [numeric] (19, 4) NULL,
[tixseatsold] [smallint] NULL,
[tixseatpaid] [smallint] NULL,
[tixseatrenewable] [smallint] NULL,
[tixseatthiseventownersuserid] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatnexteventownersuserid] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatholdexpiration] [datetime2] (6) NULL,
[tixseatsoldfromoutlet] [numeric] (10, 0) NULL,
[tixseatprintbatchid] [numeric] (10, 0) NULL,
[tixseatpackageon] [smallint] NULL,
[tixseatpackage] [int] NULL,
[tixseatpackageid] [numeric] (10, 0) NULL,
[tixseatspecialtycode_ctrlreqd] [smallint] NULL,
[tixseatspecialtycode_ctrlopt] [numeric] (10, 0) NULL,
[tixseatlastupdate] [datetime2] (6) NULL,
[tixseatprintable] [smallint] NULL,
[tixseatprinted] [smallint] NULL,
[tixseatshipdate] [datetime2] (6) NULL,
[tixseatshipservecharge] [numeric] (19, 4) NULL,
[tixseatrenewalexpiredate] [datetime2] (6) NULL,
[tixseatprojectedprice] [numeric] (19, 4) NULL,
[tixseateventtype] [smallint] NULL,
[tixseatprintfilename] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatpkgpricecode] [smallint] NULL,
[tixseatmod] [numeric] (10, 0) NULL,
[tixseatshippingoption] [numeric] (10, 0) NULL,
[tixseattrackingnumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatofferid] [numeric] (20, 0) NULL,
[tixseatlastscandate] [datetime2] (6) NULL,
[tixseatoffergroupid] [numeric] (20, 0) NULL,
[tixseatordergroupid] [numeric] (20, 0) NULL,
[tixseatinfo1] [numeric] (10, 0) NULL,
[tixseatinfo2] [numeric] (10, 0) NULL,
[tixseatlocked] [smallint] NULL,
[change_group_id] [numeric] (10, 0) NULL,
[seat_bit_flags] [int] NULL,
[tixhandheldmessage_id] [int] NULL,
[tixseatdisplayorder] [numeric] (10, 0) NULL,
[paper_converted] [smallint] NULL
)
GO
ALTER TABLE [bkp].[SSIS_VTX_tixeventzoneseats] ADD CONSTRAINT [PK__SSIS_VTX__C4EA24453970DE5E] PRIMARY KEY CLUSTERED  ([ETL__ID])
GO
