CREATE TABLE [bkp].[Sync_temp_ods_VTX_tixeventzoneseatgroups]
(
[tixeventid] [decimal] (10, 0) NOT NULL,
[tixeventzoneid] [int] NOT NULL,
[tixseatgroupid] [int] NOT NULL,
[tixseatgroupdesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tixseatgrouptype] [int] NOT NULL,
[tixseatgroupdisplayorder] [int] NULL,
[tixseatgroupparentgroup] [int] NULL,
[tixseatgroupgrandparent] [int] NULL,
[tixseatgroupgreatgrandparent] [int] NULL,
[tixseatgrouplevelsfromevent] [int] NOT NULL,
[tixseatgrouptotalingroup] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalonsale] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalremaining] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalkills] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalcomps] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalonhold] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalsold] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalnonallocsold] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalprinted] [decimal] (10, 0) NOT NULL,
[tixseatgrouppricelevel] [decimal] (10, 0) NULL,
[tixseatgroupsalepriority] [decimal] (10, 0) NULL,
[tixseatgroupmultiavailstatflag] [int] NOT NULL,
[tixseatgroupprimaryspeccode] [int] NULL,
[tixseatgrouptotalnonallocpaid] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalpaid] [decimal] (10, 0) NOT NULL,
[tixseatgroupnonallocpaidbucks] [decimal] (19, 4) NOT NULL,
[tixseatgroupnonallocsoldbucks] [decimal] (19, 4) NOT NULL,
[tixseatgrouppaidbucks] [decimal] (19, 4) NOT NULL,
[tixseatgroupsoldbucks] [decimal] (19, 4) NOT NULL,
[tixseatgroupnonallocpaidvalue] [decimal] (19, 4) NOT NULL,
[tixseatgroupnonallocsoldvalue] [decimal] (19, 4) NOT NULL,
[tixseatgrouppaidvalue] [decimal] (19, 4) NOT NULL,
[tixseatgroupsoldvalue] [decimal] (19, 4) NOT NULL,
[tixseatgroupsoldtod8] [decimal] (19, 4) NOT NULL,
[tixseatgroupnonallocsoldtod8] [decimal] (19, 4) NOT NULL,
[tixseatgroupcompsvalue] [decimal] (19, 4) NOT NULL,
[tixseatgroupflashmovieframeid] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgroupcompassright] [int] NULL,
[tixseatgroupcompassleft] [int] NULL,
[tixseatgroupcompassup] [int] NULL,
[tixseatgroupcompassdown] [int] NULL,
[tixseatgrouplevelstoseats] [int] NULL,
[tixeventzoneseatgrouplastupd] [datetime2] NULL,
[tixseatgroupseatrequestgroup] [int] NULL,
[tixseatgrouptotalnonalloccomp] [decimal] (10, 0) NOT NULL,
[tixseatgroupnonalloccompsvalue] [decimal] (19, 4) NOT NULL,
[tixseatgroupsaleorder] [decimal] (10, 0) NULL,
[tixseatgrouptotalingroup_nona] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalonsale_nona] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalremain_nona] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalonhold_nona] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalkills_nona] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalallocations] [decimal] (10, 0) NOT NULL,
[tixseatgrouptotalconsign] [decimal] (10, 0) NOT NULL,
[tixseatgroupconsignprice] [decimal] (19, 4) NOT NULL,
[tixseatgroupprintdesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tixseatgroupflashmovietype] [int] NULL,
[tixseatgroupavailableforweb] [int] NOT NULL,
[tixseatgroupcenterindicator] [int] NULL,
[tixseatgroupdisplayasga] [int] NULL,
[tixseatgroupaddlinfo] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseatgroupgaseatdescription] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_tixeventzoneseatgroups] ADD CONSTRAINT [PK__Sync_tem__19364FD2124A3B6A] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
