CREATE TABLE [bkp].[Sync_temp_ods_VTX_users]
(
[userid] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[userlastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userfirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usermiddle] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userfax1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userage] [decimal] (10, 0) NULL,
[userisfemale] [int] NULL,
[useraddress1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useraddress2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useraddress3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercity] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userst] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercountry] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userzip] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useremail1] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useremail2] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userinitdate] [datetime2] NULL,
[userlastupdate] [datetime2] NULL,
[userexpiredate] [datetime2] NULL,
[userlevel] [int] NULL,
[usergroups] [nvarchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpwd_obsolete] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userloginadmincode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userquestionslist] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[verifyuserpassword] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userprimarycc] [int] NULL,
[userconnectionspeed] [int] NULL,
[usersslpreference] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersubscriptiongroup] [int] NULL,
[userloginadmincodeeffective] [datetime2] NULL,
[usernotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useradminnotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpreferredsearchlevel] [int] NULL,
[useremailliststatus] [int] NULL,
[userpublicidentityoption] [int] NULL,
[usersecuritygroup1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup5] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup6] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup7] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpreventinboundemail] [int] NULL,
[userdemographicgroup] [int] NULL,
[userstatecode] [int] NULL,
[userinitialep] [int] NULL,
[usercompanyname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup8] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[archivedsessions] [decimal] (10, 0) NULL,
[archivedpagecount] [decimal] (10, 0) NULL,
[archivedbannercount] [decimal] (10, 0) NULL,
[userlastlogin] [datetime2] NULL,
[userbirthday] [datetime2] NULL,
[usersessioncontrol] [decimal] (10, 0) NULL,
[userpreferredemailtype] [int] NULL,
[userfullname] [nvarchar] (456) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpasswordexpires] [datetime2] NULL,
[useraccountnumber] [nvarchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercountycode] [int] NULL,
[userprefix] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersuffix] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercounty] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userlastupdatedby] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userspouse] [nvarchar] (156) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useroldaccountnumber] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userallowsingleloginonly] [int] NULL,
[userpreferredlanguageid] [int] NULL,
[userstatecodedesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone1type] [int] NULL,
[userphone2type] [int] NULL,
[userphone3type] [int] NULL,
[usersalutation] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersearch] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercareof] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [decimal] (10, 0) NULL,
[userpasswordhash] [nvarchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_users] ADD CONSTRAINT [PK__Sync_tem__19364FD2FC7623E3] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
