CREATE TABLE [bkp].[Sync_temp_ods_VTX_establishments]
(
[establishmenttype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[establishmentkey] [decimal] (10, 0) NOT NULL,
[establishmentfullname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentdescription] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcompanyname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaffilation] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentownership] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress1] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress2] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentaddress3] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcity] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentstate] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentstatecode] [int] NULL,
[establishmentzip] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentcountry] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentlocationcode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentdirectline] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenttollfreeinstate] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenttollfreeoutstate] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentexecofficenumber] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentpublicemail] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmenthomepage] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecuritygroup4] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsitecreated] [datetime2] NULL,
[establishmentinitdate] [datetime2] NULL,
[establishmentsuggestedby] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsuggestedbystring] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentlastupdatewhen] [datetime2] NULL,
[establishmentlastupdatewho] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentquicknavcode] [decimal] (10, 0) NULL,
[establishmentremoteadmincode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerfilename] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerorigfile] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbanneruploadwhen] [datetime2] NULL,
[establishmentbanneruploadwho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannersizebytes] [decimal] (10, 0) NULL,
[establishmentbannersizewidth] [decimal] (10, 0) NULL,
[establishmentbannersizeheight] [decimal] (10, 0) NULL,
[establishmentbannerapproved] [int] NOT NULL,
[establishmentbannerapprovewhen] [datetime2] NULL,
[establishmentbannerapprovewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentbannerswap] [int] NOT NULL,
[establishmentlinkexchange] [int] NOT NULL,
[establishmentbannerweightperc] [decimal] (38, 10) NULL,
[establishmentbannerweightshar] [decimal] (38, 10) NULL,
[establishmentbannertimemult] [decimal] (38, 10) NULL,
[establishmentevtschedstatus] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedlimitlist] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedsysname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedmaxdb1rec] [decimal] (10, 0) NULL,
[establishmentevtschedmaxdb2rec] [decimal] (10, 0) NULL,
[establishmentevtscheddb1name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2name] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1item] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2item] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1refint] [int] NOT NULL,
[establishmentevtscheddb2refint] [int] NOT NULL,
[establishmentevtschedeventname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedeventitem] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1mode] [int] NULL,
[establishmentevtscheddb2mode] [int] NULL,
[establishmentevtscheddefltdb1] [int] NOT NULL,
[establishmentevtscheddb1type] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb1key] [decimal] (10, 0) NULL,
[establishmentevtscheddb1id] [decimal] (10, 0) NULL,
[establishmentevtscheddb2type] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2key] [decimal] (10, 0) NULL,
[establishmentevtscheddb2id] [decimal] (10, 0) NULL,
[establishmentevtscheddb2pname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtscheddb2pitem] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedcalline3] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschedmmmaxbyte] [decimal] (10, 0) NULL,
[establishmentevtschedmaxestrec] [decimal] (10, 0) NULL,
[establishmentevtscheddefltdays] [decimal] (10, 0) NULL,
[establishmentevtschedlinkcntrl] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentprimarytype] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentsecondarytype] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubstatus] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfaxnumber] [nvarchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentvthomepage] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubnewmembers] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentvtphotospage] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmententrypoint] [int] NULL,
[establishmentcountycode] [int] NULL,
[usercountycode] [int] NULL,
[establishmentbannernotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentevtschednotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentfanclubnewmemberm] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[establishmentnotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[spacebisonenabled] [int] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_establishments] ADD CONSTRAINT [PK__Sync_tem__19364FD2942E8CE5] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
