CREATE TABLE [bkp].[Sync_temp_ods_VTX_tixeventzones]
(
[tixeventid] [decimal] (10, 0) NOT NULL,
[tixeventzoneid] [int] NOT NULL,
[tixeventonsale] [datetime2] NOT NULL,
[tixeventinitdate] [datetime2] NOT NULL,
[tixeventlastupdwhen] [datetime2] NULL,
[tixeventlastupdatewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventbuiltfromseatmap] [decimal] (10, 0) NULL,
[tixeventseatmaplocked] [int] NOT NULL,
[tixeventstatus] [int] NULL,
[tixeventtopseatgrouptype] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventtourid] [int] NULL,
[tixeventticketformat] [int] NULL,
[tixeventtotalseats] [decimal] (10, 0) NOT NULL,
[tixeventtotalonsale] [decimal] (10, 0) NOT NULL,
[tixeventtotalremaining] [decimal] (10, 0) NOT NULL,
[tixeventtotalkills] [decimal] (10, 0) NOT NULL,
[tixeventtotalcomps] [decimal] (10, 0) NOT NULL,
[tixeventtotalonhold] [decimal] (10, 0) NOT NULL,
[tixeventtotalsold] [decimal] (10, 0) NOT NULL,
[tixeventtotalnonallocsold] [decimal] (10, 0) NOT NULL,
[tixeventtotalprinted] [decimal] (10, 0) NOT NULL,
[tixeventzonedesc] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tixeventzonedispord] [int] NULL,
[tixeventzonetype] [int] NOT NULL,
[tixeventinventorysecurityincl] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventinventorysearchinclude] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneonsale] [int] NULL,
[tixeventzonereadyforsale] [int] NULL,
[tixeventzonenexteventid] [decimal] (10, 0) NULL,
[tixeventzonepreveventid] [decimal] (10, 0) NULL,
[tixeventzonenextzoneid] [int] NULL,
[tixeventzoneprevzoneid] [int] NULL,
[evtschedeventdb1estabtype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[evtschedeventdb1estabkey] [decimal] (10, 0) NULL,
[tixeventtotalpaid] [decimal] (10, 0) NOT NULL,
[tixeventtotalnonallocpaid] [decimal] (10, 0) NOT NULL,
[tixeventtotalsoldbucks] [decimal] (19, 4) NOT NULL,
[tixeventtotalnonallocsoldbucks] [decimal] (19, 4) NOT NULL,
[tixeventtotalpaidbucks] [decimal] (19, 4) NOT NULL,
[tixeventtotalnonallocpaidbucks] [decimal] (19, 4) NOT NULL,
[tixeventtotalsoldtod8] [decimal] (19, 4) NOT NULL,
[tixeventtotalnonallocsoldtod8] [decimal] (19, 4) NOT NULL,
[tixeventtotalsoldvalue] [decimal] (19, 4) NOT NULL,
[tixeventtotalpaidvalue] [decimal] (19, 4) NOT NULL,
[tixeventtotalnonallocsoldvalue] [decimal] (19, 4) NOT NULL,
[tixeventtotalnonallocpaidvalue] [decimal] (19, 4) NOT NULL,
[tixeventtotalcompsvalue] [decimal] (19, 4) NOT NULL,
[tixeventzonefullauditactive] [int] NOT NULL,
[tixeventflashmovieid] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixevtznproductvendortype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixevtznproductvendorkey] [decimal] (10, 0) NULL,
[tixevtznproductid] [decimal] (10, 0) NULL,
[tixevtznavailabilitymsg] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneallowsingles] [int] NOT NULL,
[tixevtznseatrequestseatgroup] [int] NULL,
[tixeventtotalnonalloccomp] [decimal] (10, 0) NOT NULL,
[tixeventtotalnonalloccompvalue] [decimal] (19, 4) NOT NULL,
[tixevtznallowseatrequests] [int] NULL,
[tixevtznseatrequestdate] [datetime2] NULL,
[tixeventzonenexthistoryid] [int] NOT NULL,
[tixeventpricechartlocked] [int] NOT NULL,
[tixeventeventlocked] [int] NOT NULL,
[tixeventzonenexterrorcheckid] [int] NOT NULL,
[tixeventzonerenewablefornextyr] [int] NOT NULL,
[tixeventoffsale] [datetime2] NULL,
[tixeventzonesectionpriormulti] [int] NOT NULL,
[tixevent_nba_rowsizefactor] [int] NOT NULL,
[tixevtznrunbackgroundintegchk] [int] NULL,
[tixevtznseatrequestsonsale] [int] NOT NULL,
[tixevtznlastsccssfulintegchkd8] [datetime2] NULL,
[tixeventzonedisplay5nba1] [decimal] (10, 0) NULL,
[tixeventzonedisplay5nba2] [decimal] (10, 0) NULL,
[tixeventzonedisplay5nba3] [decimal] (10, 0) NULL,
[tixeventzonedisplay5nba4] [decimal] (10, 0) NULL,
[tixeventtotalseats_nona] [decimal] (10, 0) NOT NULL,
[tixeventtotalonsale_nona] [decimal] (10, 0) NOT NULL,
[tixeventtotalremaining_nona] [decimal] (10, 0) NOT NULL,
[tixeventtotalonhold_nona] [decimal] (10, 0) NOT NULL,
[tixeventtotalkills_nona] [decimal] (10, 0) NOT NULL,
[tixeventtotalallocations] [decimal] (10, 0) NOT NULL,
[tixevtznglcode] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventtotalconsign] [decimal] (10, 0) NOT NULL,
[tixeventconsignprice] [decimal] (19, 4) NOT NULL,
[tixeventzoneavailableforweb] [int] NOT NULL,
[tixeventzoneusestopcard] [int] NOT NULL,
[tixeventzoneiscanceled] [int] NULL,
[tixeventzonecancellationdate] [datetime2] NULL,
[tixeventzonecancellationreason] [nvarchar] (600) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[display_in_reports] [int] NOT NULL,
[tixeventzoneeticketline1] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline2] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline3] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline4] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline5] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventzoneeticketline6] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixtransferfeeenabled] [decimal] (38, 10) NULL,
[tixeventzoneallowtixforwarding] [int] NOT NULL,
[tixeventzoneallowonlinepayment] [int] NOT NULL,
[ac_lasthistoryptr] [decimal] (20, 0) NULL,
[ac_exportzone] [int] NULL,
[product_id] [decimal] (20, 0) NULL,
[venue_map_id] [decimal] (20, 0) NULL,
[is_published] [int] NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[event_owner_id] [decimal] (10, 0) NULL,
[accesscontrolenddatetime] [datetime2] NULL,
[accesscontrolstartdatetime] [datetime2] NULL,
[enableaccesscontrol] [int] NULL,
[tixeventzoneversion] [decimal] (18, 0) NULL,
[tixeventzonemaxentry] [int] NULL,
[tixeventzonemaxperday] [int] NULL,
[tixeventzoneentryexit] [int] NULL,
[stadis_active] [int] NULL,
[stadis_exported] [int] NULL,
[stadis_lasthistoryptr] [decimal] (20, 0) NULL,
[sales_restrict] [int] NULL,
[convertfsunpaid] [int] NULL,
[seatmap_image_id] [decimal] (18, 0) NULL,
[seatmap_image_mode] [int] NULL,
[enable_paper_conversion] [int] NULL,
[waive_paper_conversion_fee] [int] NULL,
[salespricechartversion] [decimal] (18, 0) NULL,
[printpricechartversion] [decimal] (18, 0) NULL,
[textpricechartversion] [decimal] (18, 0) NULL,
[single_forward] [int] NULL,
[tax_profile_id] [decimal] (20, 0) NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_tixeventzones] ADD CONSTRAINT [PK__Sync_tem__19364FD253310FAD] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
