CREATE TABLE [bkp].[Sync_temp_ods_VTX_ordergroups]
(
[ordergroup] [decimal] (10, 0) NOT NULL,
[ordergroupsegregationcode] [int] NULL,
[ordergrouppaymentmode] [int] NULL,
[ordergroupshipservechargemode] [int] NULL,
[ordergroupmasterorderid] [decimal] (10, 0) NULL,
[ordergroupinituser] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupenteredby] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouporiginaltotal] [decimal] (19, 4) NULL,
[ordergroupgrandtotal] [decimal] (19, 4) NULL,
[ordergrouptotaldiscounts] [decimal] (19, 4) NULL,
[ordergrouptotaltax] [decimal] (19, 4) NULL,
[ordergroupshippingtotal] [decimal] (19, 4) NULL,
[ordergroupshippingdiscounts] [decimal] (19, 4) NULL,
[ordergroupshippingtax] [decimal] (19, 4) NULL,
[ordergroupservicechgtotal] [decimal] (19, 4) NULL,
[ordergroupservicechgdiscount] [decimal] (19, 4) NULL,
[ordergroupservicechgtax] [decimal] (19, 4) NULL,
[ordergrouptotalpaymentsreq] [decimal] (19, 4) NULL,
[ordergrouptotalaltpayments] [decimal] (19, 4) NULL,
[ordergrouprelatedestabtype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouprelatedestabkey] [decimal] (10, 0) NULL,
[ordergroupordertype] [int] NULL,
[ordergroupsingleormultiuser] [int] NULL,
[ordergroupshippingdestmode] [int] NULL,
[ordergrouprelatedestabrelation] [int] NULL,
[ordergroupshipname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipaddress1] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipaddress2] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipcity] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipst] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipcountry] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipzip] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupshipstatecode] [int] NULL,
[ordergroupshippingzone] [int] NULL,
[ordergroupshippingzoneinvalid] [int] NULL,
[usercountycode] [int] NULL,
[ordergroupinitialep] [int] NULL,
[ordergroupcheckoutep] [int] NULL,
[ordergroupshipcountycode] [int] NULL,
[ordergroupuserid] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergroupconfirmationnumber] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouptimetoplaceorder] [decimal] (10, 0) NULL,
[ordergroupbottomlineorigtotal] [decimal] (19, 4) NULL,
[ordergroupbottomlinegrandtotal] [decimal] (19, 4) NULL,
[ordergroupbottomlineactivtotal] [decimal] (19, 4) NULL,
[ordergroupbottomlinetotaltax] [decimal] (19, 4) NULL,
[ordergroupbottomlinetotaldisc] [decimal] (19, 4) NULL,
[ordergroupactivetotal] [decimal] (19, 4) NULL,
[ordergroupshippingactivetotal] [decimal] (19, 4) NULL,
[ordergroupservicechgactivtotal] [decimal] (19, 4) NULL,
[ordergrouptotalpaymentscleared] [decimal] (19, 4) NULL,
[ordergrouptotalpaymentsonhold] [decimal] (19, 4) NULL,
[ordergrouptotalpaymentsinqueue] [decimal] (19, 4) NULL,
[ordergrouppaymentbalance] [decimal] (19, 4) NULL,
[ordergroupdate] [datetime2] NULL,
[ordergroupclosedondate] [datetime2] NULL,
[ordergroupstatus] [int] NULL,
[ordergrouptimetocompleteorder] [decimal] (10, 0) NULL,
[ordergroupclosed] [int] NULL,
[ordergrouplastupdated] [datetime2] NULL,
[ordergroupinvoicenumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[commentid] [decimal] (10, 0) NULL,
[ordergroupoutletid] [decimal] (10, 0) NULL,
[ordergrouppaymentstatus] [int] NULL,
[eticketemail] [nvarchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customerid] [decimal] (38, 10) NULL,
[willcallcode] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addressid] [decimal] (10, 0) NULL,
[willcallname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[tickets_ever_in_fs] [int] NULL,
[convertfsunpaid] [int] NULL,
[tags] [nvarchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ordergrouppaymentbypass] [int] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_ordergroups] ADD CONSTRAINT [PK__Sync_tem__19364FD21D569AD6] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
