CREATE TABLE [bkp].[Sync_temp_ods_VTX_tixevents]
(
[tixeventid] [decimal] (10, 0) NOT NULL,
[tixeventtitleshort] [nvarchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[tixeventtitlelong] [nvarchar] (3072) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventonsale] [datetime2] NOT NULL,
[tixeventstartdate] [datetime2] NOT NULL,
[tixeventenddate] [datetime2] NULL,
[tixeventgatesopen] [datetime2] NULL,
[tixeventtourid] [int] NULL,
[tixeventlookupid] [nvarchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventinitdate] [datetime2] NOT NULL,
[tixeventlastupdwhen] [datetime2] NULL,
[tixeventlastupdatewho] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventtype] [int] NOT NULL,
[tixeventemailnotifydate] [datetime2] NULL,
[tixeventcategoryid] [decimal] (38, 10) NULL,
[establishmenttype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixrenewalid] [decimal] (38, 10) NULL,
[tixeventcurrentuntil] [datetime2] NULL,
[display_in_reports] [int] NOT NULL,
[tixeventdisplaydate] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventimagepath] [nvarchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventsoundfilepath] [nvarchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventvisible] [int] NULL,
[eticketschedule] [datetime2] NULL,
[allowcontinueshopping] [int] NULL,
[venueestablishmenttype] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venueestablishmentkey] [decimal] (10, 0) NULL,
[ac_exportevent] [int] NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[flashseats_schedule] [datetime2] NULL,
[tixeventversion] [decimal] (18, 0) NULL,
[tixeventkeywords] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixeventinternalinformation] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[web_tracking_profile_id] [decimal] (10, 0) NULL,
[default_offer_id] [decimal] (18, 0) NULL,
[visible_to_web] [int] NULL,
[image_id] [decimal] (18, 0) NULL,
[flasheventid] [decimal] (38, 10) NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [bkp].[Sync_temp_ods_VTX_tixevents] ADD CONSTRAINT [PK__Sync_tem__19364FD2B0974A68] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
