CREATE TABLE [dbo].[One-Time_Data_Append_032917]
(
[cvFirstName1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvMiddleName1] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvLastName1] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvSuffixTitle1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvPrimaryBusiness] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasPriAddress] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasSecAddress] [varchar] (129) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasCityName] [varchar] (63) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasStateAbrev] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasZIPCode] [int] NULL,
[pasAddonCode] [smallint] NULL,
[pasDelPtCode] [smallint] NULL,
[pasCarrierID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDPVReturnCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDSFAddressType] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDSFDeliverabilityInd] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source] [varchar] (33) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Accounts] [real] NULL,
[Last Name] [varchar] (114) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (99) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (168) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2] [varchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (87) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (39) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP Code] [int] NULL,
[EmailAddress] [varchar] (132) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Edit Fail] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lacLinks_Returned_Code] [smallint] NULL,
[Personicx Lifestage Cluster Code] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Community Involvement - Causes Supported Financially] [bigint] NULL,
[Business Owner] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Veteran] [smallint] NULL,
[Occupation - Detail - Input Individual] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Religious   Inspirational] [smallint] NULL,
[Investments - Personal] [smallint] NULL,
[Investments - Real Estate] [smallint] NULL,
[Investments - Stocks   Bonds] [smallint] NULL,
[Boating   Sailing] [smallint] NULL,
[Vehicle - Truck Motorcycle RV Owner] [smallint] NULL,
[Mail Order Buyer Categories] [bigint] NULL,
[Mail Order Donor] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Property Type Detail (RP)] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Year Built - Actual (RP)] [smallint] NULL,
[Adult Age Ranges Present in Household] [bigint] NULL,
[Children's Age Ranges Present in Household] [bigint] NULL,
[Occupation - 1st Individual] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 2nd Individual] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Owner   Renter] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Length of Residence] [smallint] NULL,
[Dwelling Type] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital Status] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name   Gender - 1st Individual] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name   Gender - 2nd Individual] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base Record Verification Date] [smallint] NULL,
[Mail Order Buyer] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 1st Individual] [smallint] NULL,
[Age in Two-Year Increments - 2nd Individual] [smallint] NULL,
[Working Woman] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Responder] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card Indicator] [int] NULL,
[Presence of Children] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - Input Individual] [smallint] NULL,
[Number of Adults] [smallint] NULL,
[Occupation - Input Individual] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InfoBase Positive Match Indicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Sources] [smallint] NULL,
[Income - Estimated Household] [smallint] NULL,
[Home Market Value - Estimated - Ranges] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Car Buyer] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Known Owned Number] [smallint] NULL,
[Vehicle - Dominant Lifestyle Indicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Online Purchasing Indicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - Input Individual] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Match Indicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card - Frequency of Purchase] [datetime] NULL,
[Retail Activity Date of Last] [int] NULL,
[Retail Purchases - Categories] [bigint] NULL,
[Retail Purchases - Most Frequent Category] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 1st Individual] [smallint] NULL,
[Education - 2nd Individual] [smallint] NULL,
[Education - Input Individual] [smallint] NULL,
[Suppression - Mail - DMA] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Classic Car Owner] [smallint] NULL
)
GO
