CREATE TABLE [ods].[VTX_payments]
(
[paymentid] [decimal] (10, 0) NOT NULL,
[paymentccbatchid] [decimal] (10, 0) NULL,
[paymenttranstype] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentusercckey] [int] NULL,
[paymentamount] [decimal] (19, 4) NOT NULL,
[paymentauthcode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentrefnumber] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentdate] [datetime2] NULL,
[paymentsetup] [datetime2] NULL,
[paymentsetdown] [datetime2] NULL,
[paymentmerchid] [int] NULL,
[paymentname] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentaddress1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentaddress2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentcity] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentst] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentcountry] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentzip] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentstatecode] [int] NULL,
[paymentrelatedpaymentid] [decimal] (10, 0) NULL,
[paymentsetdownperforminguser] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttransactiondate] [datetime2] NULL,
[paymentuserccvalidcoderesponse] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentcardentryindicator] [int] NULL,
[paymentproviderresponsecode] [int] NULL,
[paymenthostresponsemessage] [varchar] (240) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenthostresponsecode] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentavsresultcode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentuserccname] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentuserccexp] [datetime2] NULL,
[paymentusercctype] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentsetupperforminguser] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymentstatus] [decimal] (10, 0) NULL,
[paymentresult] [decimal] (10, 0) NULL,
[paymentoutletid] [int] NULL,
[paymentchannel] [int] NULL,
[paymentsetupoutletid] [int] NULL,
[customerid] [decimal] (38, 10) NULL,
[ordergroupid] [decimal] (20, 0) NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[paymentusercclastfour] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cctransactiontype] [int] NULL,
[provider_response_details] [varchar] (3000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_token_id] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_first_six] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[application_id] [int] NULL,
[paymentprocessorresponsecode] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cc_hash_info_id] [decimal] (10, 0) NULL,
[ach_acct_id] [decimal] (38, 0) NULL,
[forte_trans_token] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL,
[ETL_Sync_UpdatedDate] [datetime] NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__VTX_payments] ON [ods].[VTX_payments]
GO
