CREATE TABLE [ods].[VTX_products]
(
[productvendortype] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvendorkey] [decimal] (10, 0) NULL,
[productid] [decimal] (10, 0) NULL,
[producttype] [int] NULL,
[productdescription] [varchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdetails2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdetails3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productdefaultmerchid] [int] NULL,
[productvendorstocknumber] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvendorcostmethod] [int] NULL,
[productvendorcosttable] [int] NULL,
[productvendorcost] [decimal] (19, 4) NULL,
[productvendorcostrate2] [decimal] (19, 4) NULL,
[productvendorcostrate3] [decimal] (19, 4) NULL,
[productusercostmethod] [int] NULL,
[productusercosttable] [int] NULL,
[productusercost] [decimal] (19, 4) NULL,
[productqty] [decimal] (38, 10) NULL,
[productunits] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productshipinitzip] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productavailable] [int] NOT NULL,
[productdisplaytousers] [int] NOT NULL,
[productdisplayorder] [int] NULL,
[producttimeoutdays] [decimal] (38, 10) NULL,
[productsearchgroups] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[producttaxtable] [int] NULL,
[productsplittable] [int] NOT NULL,
[productinitdate] [datetime2] NULL,
[productlastupdatewhen] [datetime2] NULL,
[productlastupdatewho] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[producttaxpoint] [int] NULL,
[productspecialprocessing] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productteaserstoryid] [decimal] (10, 0) NULL,
[productinfostoryid] [decimal] (10, 0) NULL,
[productvolumediscountcategory] [int] NULL,
[prodvolumediscountsubcategory] [int] NULL,
[prodvolumediscountdiscntcode] [int] NULL,
[prodvolumediscountdiscntentry] [int] NULL,
[prodoutofstockfullfillprocess] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodinstockfullfillmentprocess] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodcustomvolumediscountinplay] [int] NOT NULL,
[prodsubscriptfreetimedatepart] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodsubscripfreetimeincrement] [int] NULL,
[prodincrementloyaltypntprogram] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prodloyaltypntprogramincrement] [varchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productcustomshipserveinplay] [int] NOT NULL,
[productdetails4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productonsalediscount] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productshipinitstate] [int] NULL,
[productshipinitcounty] [int] NULL,
[productcurrentstockquantity] [decimal] (10, 0) NULL,
[productlowstocklevelquantity] [decimal] (10, 0) NULL,
[productdetails] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productvalidshippingoptions] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productaddadvsecroles] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productadduserretrcodes] [varchar] (192) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productglcode] [varchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[productinactive] [int] NOT NULL,
[refundaltpaymenttype] [decimal] (10, 0) NULL,
[productentityid] [int] NULL,
[productdisplaydescription] [varchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[channel1merchid] [int] NULL,
[channel2merchid] [int] NULL,
[channel3merchid] [int] NULL,
[channel4merchid] [int] NULL,
[channel5merchid] [int] NULL,
[id] [decimal] (20, 0) NOT NULL,
[client_id] [decimal] (10, 0) NOT NULL,
[settlement_code_id] [decimal] (18, 0) NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL,
[ETL_Sync_UpdatedDate] [datetime] NULL
)
GO
CREATE NONCLUSTERED INDEX [IDX_id] ON [ods].[VTX_products] ([id])
GO
