CREATE TABLE [ods].[VTX_offers]
(
[id] [decimal] (20, 0) NOT NULL,
[lookup] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[name] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[description] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[display_date] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sort_date] [datetime2] NULL,
[promotion_code] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[on_sale_date] [datetime2] NULL,
[off_sale_date] [datetime2] NULL,
[ae_user_id] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ae_role_id] [decimal] (20, 0) NULL,
[use_user_ssc] [int] NOT NULL,
[min_qty] [decimal] (10, 0) NULL,
[max_qty] [decimal] (10, 0) NULL,
[customer_list_id] [decimal] (20, 0) NULL,
[pref_fee_target] [decimal] (20, 0) NULL,
[published] [int] NULL,
[list_online] [int] NOT NULL,
[is_draft] [int] NOT NULL,
[image] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [decimal] (10, 0) NULL,
[allow_public_seat_change] [int] NOT NULL,
[require_contiguous_seats] [int] NOT NULL,
[allow_empty_single_seats] [int] NOT NULL,
[additional_info1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[additional_info2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customer_restriction_count] [decimal] (10, 0) NULL,
[has_account_restriction] [int] NULL,
[has_pass_code_restriction] [int] NULL,
[has_sign_in_restriction] [int] NULL,
[system_type] [int] NULL,
[timer_profile_id] [int] NULL,
[default_restrict_transfer] [int] NULL,
[default_restrict_resale] [int] NULL,
[default_waive_first_seller_fee] [int] NULL,
[osearch] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fs_redirect] [int] NULL,
[offerlabel] [int] NULL,
[version] [decimal] (18, 0) NULL,
[tags] [varchar] (1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[offer_image_id] [decimal] (18, 0) NULL,
[mobile_image_id] [decimal] (18, 0) NULL,
[allow_additional_donation_ots] [int] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL,
[ETL_Sync_UpdatedDate] [datetime] NULL
)
GO
