CREATE TABLE [ods].[VTX_users]
(
[userid] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[userlastname] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userfirstname] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usermiddle] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userfax1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userage] [decimal] (10, 0) NULL,
[userisfemale] [int] NULL,
[useraddress1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useraddress2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useraddress3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercity] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userst] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercountry] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userzip] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useremail1] [varchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useremail2] [varchar] (765) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userinitdate] [datetime2] NULL,
[userlastupdate] [datetime2] NULL,
[userexpiredate] [datetime2] NULL,
[userlevel] [int] NULL,
[usergroups] [varchar] (384) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpwd_obsolete] [varchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userloginadmincode] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userquestionslist] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[verifyuserpassword] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userprimarycc] [int] NULL,
[userconnectionspeed] [int] NULL,
[usersslpreference] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersubscriptiongroup] [int] NULL,
[userloginadmincodeeffective] [datetime2] NULL,
[usernotes] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useradminnotes] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpreferredsearchlevel] [int] NULL,
[useremailliststatus] [int] NULL,
[userpublicidentityoption] [int] NULL,
[usersecuritygroup1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup6] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup7] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpreventinboundemail] [int] NULL,
[userdemographicgroup] [int] NULL,
[userstatecode] [int] NULL,
[userinitialep] [int] NULL,
[usercompanyname] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersecuritygroup8] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[archivedsessions] [decimal] (10, 0) NULL,
[archivedpagecount] [decimal] (10, 0) NULL,
[archivedbannercount] [decimal] (10, 0) NULL,
[userlastlogin] [datetime2] NULL,
[userbirthday] [datetime2] NULL,
[usersessioncontrol] [decimal] (10, 0) NULL,
[userpreferredemailtype] [int] NULL,
[userfullname] [varchar] (456) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userpasswordexpires] [datetime2] NULL,
[useraccountnumber] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercountycode] [int] NULL,
[userprefix] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersuffix] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercounty] [varchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userlastupdatedby] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userspouse] [varchar] (156) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[useroldaccountnumber] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userallowsingleloginonly] [int] NULL,
[userpreferredlanguageid] [int] NULL,
[userstatecodedesc] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[userphone1type] [int] NULL,
[userphone2type] [int] NULL,
[userphone3type] [int] NULL,
[usersalutation] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usersearch] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[usercareof] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_id] [decimal] (10, 0) NULL,
[userpasswordhash] [varchar] (144) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL,
[ETL_Sync_UpdatedDate] [datetime] NULL
)
GO
