CREATE TABLE [ods].[VTX_TixEventZoneSeatHistory]
(
[tixeventid] [numeric] (10, 0) NULL,
[tixeventzoneid] [smallint] NULL,
[tixseatgroupid] [int] NULL,
[tixseatid] [numeric] (10, 0) NULL,
[tixseathistoryptr] [numeric] (20, 0) NULL,
[tixseathistorystatus] [numeric] (10, 0) NULL,
[tixseathistorypreviousstatus] [numeric] (10, 0) NULL,
[tixseathistorystatustype] [smallint] NULL,
[tixseathistoryprevstatustype] [smallint] NULL,
[tixseathistoryecomhdr] [numeric] (10, 0) NULL,
[tixseathistoryecomdtl] [int] NULL,
[tixseathistoryuseractivbatch] [int] NULL,
[tixseathistoryuseractivcounter] [numeric] (10, 0) NULL,
[tixseathistorylink] [numeric] (10, 0) NULL,
[tixseathistorydate] [datetime2] (6) NULL,
[tixseathistoryoperatorbatch] [numeric] (10, 0) NULL,
[tixseathistoryperforminguser] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseathistorypricecode] [numeric] (10, 0) NULL,
[tixseathistorypackage] [int] NULL,
[tixseathistorypackageid] [numeric] (10, 0) NULL,
[tixseathistoryvalue] [numeric] (19, 4) NULL,
[tixseathistorypkgpricecode] [numeric] (10, 0) NULL,
[tixseathistorybarcode] [nvarchar] (96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseathistoryprintbatch] [numeric] (10, 0) NULL,
[tixseathistorydeltapaidtod8] [numeric] (19, 4) NULL,
[tixseathistoryshippingoption] [numeric] (10, 0) NULL,
[tixseathistorytrackingnumber] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tixseathistoryoutletid] [int] NULL,
[tixseathistorychannel] [smallint] NULL,
[tixseathistorypricelevel] [numeric] (10, 0) NULL,
[tixseathistoryofferid] [numeric] (20, 0) NULL,
[tixseathistoryoffergroupid] [numeric] (20, 0) NULL,
[tixseathistoryordergroupid] [numeric] (20, 0) NULL,
[change_group_id] [numeric] (10, 0) NULL,
[seat_bit_flags] [int] NULL,
[paper_converted] [smallint] NULL,
[imsseatpointer] [numeric] (20, 0) NULL,
[ETL_Sync_UpdatedDate] [datetime] NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI__ods_VTX_TixEventZoneSeatHistory] ON [ods].[VTX_TixEventZoneSeatHistory]
GO
