CREATE TABLE [stg].[LionsF16One-TimeDataAppend_032917]
(
[cvFirstName1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvMiddleName1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvLastName1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvSuffixTitle1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cvPrimaryBusiness] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasPriAddress] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasSecAddress] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasCityName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasStateAbrev] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasZIPCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasAddonCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDelPtCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasCarrierID] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDPVReturnCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDSFAddressType] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pasDSFDeliverabilityInd] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Accounts] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP Code] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailAddress] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Edit Fail] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lacLinks_Returned_Code] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personicx Lifestage Cluster Code] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Community Involvement - Causes Supported Financially] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Owner] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Veteran] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Detail - Input Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Religious   Inspirational] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investments - Personal] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investments - Real Estate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Investments - Stocks   Bonds] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Boating   Sailing] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Truck Motorcycle RV Owner] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Buyer Categories] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Donor] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Property Type Detail (RP)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Year Built - Actual (RP)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adult Age Ranges Present in Household] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Children's Age Ranges Present in Household] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 1st Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - 2nd Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Owner   Renter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Length of Residence] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dwelling Type] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Marital Status] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name   Gender - 1st Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name   Gender - 2nd Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Base Record Verification Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Buyer] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 1st Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - 2nd Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Working Woman] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mail Order Responder] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card Indicator] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Presence of Children] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age in Two-Year Increments - Input Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Adults] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation - Input Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InfoBase Positive Match Indicator] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number of Sources] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Income - Estimated Household] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Market Value - Estimated - Ranges] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - New Car Buyer] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Known Owned Number] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Dominant Lifestyle Indicator] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Online Purchasing Indicator] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender - Input Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Overall Match Indicator] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit Card - Frequency of Purchase] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Activity Date of Last] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Purchases - Categories] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retail Purchases - Most Frequent Category] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 1st Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - 2nd Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Education - Input Individual] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suppression - Mail - DMA] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vehicle - Classic Car Owner] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
