CREATE TABLE [stg].[TE_Sales]
(
[weborderid] [float] NULL,
[inettransid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ticketsource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneraccountid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneremail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicenumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[invoicedate] [datetime] NULL,
[purchaseddaysbeforeevent] [float] NULL,
[eventname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[opponentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eventdate] [datetime] NULL,
[eventtime] [datetime] NULL,
[tickettype] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatsection] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seatrow] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[startingseat] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[endingseat] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbrofseats] [float] NULL,
[postingpriceperticket] [float] NULL,
[postingpriceperorder] [float] NULL,
[markup] [float] NULL,
[sellerfeeperorder] [float] NULL,
[buyerfeeperorder] [float] NULL,
[deliveryfeeperorder] [float] NULL,
[gtv] [float] NULL,
[netrevenue] [float] NULL,
[paymenttype] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyerlastname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[buyerfirstname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addressline1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addressline2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[postalcode] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dayphone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[eveningphone] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbrofdayslisted] [float] NULL,
[ticketid] [float] NULL
)
GO
