CREATE TABLE [stg].[Fanatics_20170630]
(
[Order_Id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Fisrt_Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Last_Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Opt_In] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_Id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Category] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Sub_Category] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Id] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Name Description] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quantity_Sold] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unit_Price] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extended_Price] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Discount_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Sub_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Taxable_Sub_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Non_Taxable_Sub_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Tax_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Ship_Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Total_Paid_By_Account] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Total_Paid_By_Fan_Cash] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address0] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_City] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_State] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_Country] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_Zip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_Tel] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_Address_Attention] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address0] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address1] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address2] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address_City] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address_State] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address_Country] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bill_Address_Zip] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
