CREATE TABLE [tc].[VTX_order_items]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__StartDate] [datetime] NOT NULL,
[ETL__EndDate] [datetime] NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[id] [decimal] (18, 0) NOT NULL,
[order_id] [decimal] (10, 0) NOT NULL,
[sale_date] [datetime2] NULL,
[sale_user] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[sale_outlet] [decimal] (10, 0) NOT NULL,
[sale_channel] [decimal] (10, 0) NOT NULL,
[value] [decimal] (19, 4) NOT NULL,
[paid_amount] [decimal] (19, 4) NOT NULL,
[product_id] [decimal] (10, 0) NOT NULL,
[inventory_type] [int] NOT NULL,
[primary_product_id] [decimal] (18, 0) NULL,
[number1] [decimal] (10, 0) NULL,
[number2] [decimal] (10, 0) NULL,
[number3] [decimal] (10, 0) NULL,
[number4] [decimal] (10, 0) NULL,
[number5] [decimal] (10, 0) NULL,
[number6] [decimal] (10, 0) NULL,
[number7] [decimal] (10, 0) NULL,
[number8] [decimal] (10, 0) NULL,
[number9] [decimal] (10, 0) NULL,
[number10] [decimal] (10, 0) NULL,
[number11] [decimal] (10, 0) NULL,
[number12] [decimal] (10, 0) NULL,
[number13] [decimal] (10, 0) NULL,
[number14] [decimal] (10, 0) NULL,
[number15] [decimal] (10, 0) NULL,
[string1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[string2] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[string3] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[string4] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[string5] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[canceled] [int] NOT NULL,
[cancel_date] [datetime2] NULL,
[cancel_user] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cancel_outlet] [decimal] (10, 0) NULL,
[cancel_channel] [decimal] (10, 0) NULL,
[offer_restriction_id] [decimal] (18, 0) NULL,
[customer_restriction_id] [decimal] (18, 0) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_tc__VTX_order_items] ON [tc].[VTX_order_items]
GO
