CREATE SCHEMA [stg]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT CONTROL ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT CREATE SEQUENCE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT DELETE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT EXECUTE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT INSERT ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT REFERENCES ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT SELECT ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT TAKE OWNERSHIP ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT UPDATE ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [stg] TO [svcssbrp]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA:: [stg] TO [svcssbrp]
GO
